// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
DigitalInput* RobotMap::meowPowerNorthPole = NULL;
DigitalInput* RobotMap::meowPowerSouthPole = NULL;
AnalogPotentiometer* RobotMap::meowPowerMagicalPot = NULL;
SpeedController* RobotMap::meowPowerSpeedController1 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	meowPowerNorthPole = new DigitalInput(0);
	lw->AddSensor("MeowPower", "NorthPole", meowPowerNorthPole);
	
	meowPowerSouthPole = new DigitalInput(1);
	lw->AddSensor("MeowPower", "SouthPole", meowPowerSouthPole);
	
	meowPowerMagicalPot = new AnalogPotentiometer(0, 1.0, 0.0);
	lw->AddSensor("MeowPower", "Magical Pot", meowPowerMagicalPot);
	
	meowPowerSpeedController1 = new Talon(0);
	lw->AddActuator("MeowPower", "Speed Controller 1", (Talon*) meowPowerSpeedController1);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
